### ISSUE TITLE
use Macbook keyboard for coding control shortcut?

### ISSUE THREAD

**Issue by missyyan** [databrary/datavyu#124]
Can I use my Macbook keyboard to set onset and offset? Or any other number/symbol shortcuts? If so, how can I enable it?

**Comment by Xubes** [comment]
It's not possible to remap the playback and/or the cell update keys in the application. If you don't have the numeric keypad keys, you can use third party apps to remap keyboard shortcuts to those functions. See: https://pqrs.org/osx/karabiner/

Mac has a Keyboard preference pane to set application shortcuts, but it doesn't seem to be work for this.

**Comment by Xubes** [comment]
@missyyan I will close this issue unless you have followup questions. Currently, Mac users use a full Mac keyboard with a numeric pad or an external USB numpad—I would recommend using one of these options over a software key remapping. We hope to eventually allow shortcut key remapping in Datavyu, but that is a ways off.

**Comment by missyyan** [comment]
@Xubes I bought a USB numpad and it worked! The easiest solution! Thanks. Yes, you can close it now.
