### ISSUE TITLE
Datavyu 1.4.2. error opening older .opf files

### ISSUE THREAD

**Issue by Mc9Lum** [databrary/datavyu#125]
**Describe the bug**
Using Datavyu 1.4.2., seems to display a corrupt file when opening files that were previously saved in Datavyu 1.3.7. This applies to all files on all of our desktops when 1.4.2 is installed. When opening such a file, a grayed-out spreadsheet box appears with no way to edit/add columns, drop down menu options in the header bar are all grayed out too, with no video window or data file in the controller.

**To Reproduce**
Open the attached .opf file in Datavyu 1.4.2. If it opens normally than it's a problem with our computers?

[LEGO_S#004_Visit1_Transcription.zip](https://github.com/databrary/datavyu/files/2658460/LEGO_S.004_Visit1_Transcription.zip)

**Expected behavior**
Not this. Literally anything but this.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 10.13.6 (High Sierra)
 - Version 1.4.2 

**Additional context**

**Comment by TheoWolf** [comment]
@Mc9Lum The file opens normally in 1.4.2 version and there is no problem with the spreadsheet, whatsoever. This could be a network issue; requesting the video from the server might freeze Datavyu.
I would suggest creating a test project with Datavyu 1.4.2 and attach to it one video from the server if you have issues to save or open the OPF file previously saved, I would assume a problem with the network. @Xubes Could you please test the shared file and see if you can open it with Datavyu 1.4.2. Thanks

**Comment by Xubes** [comment]
@TheoWolf I'm checking their setup this afternoon.

**Comment by Xubes** [comment]
1.4.2 crashes when clicking Add Data. This might be blocking the spreadsheet from loading. See attached output file.

[log.txt](https://github.com/databrary/datavyu/files/2770539/log.txt)

**Comment by Xubes** [comment]
Both the file chooser dialog and the .opf file from older version work if VLC is removed. VLC version is 3.0.4
