### ISSUE TITLE
Unable to set offset using Numpad-9

### ISSUE THREAD

**Issue by Xubes** [databrary/datavyu#126]
> Currently, we are unable to offset cells using "9," but are able to offset cells using the period.  This is the case whether I hit the key or use the Data Viewer Controller.  The computer experiencing the issue is using Datavyu 1.4.1, and is running macOS Mojave 10.14.2.

**Comment by Xubes** [comment]
> Are you using the numeric pad on a full Mac keyboard or an external numpad? If it’s external I would make sure that there is no NumLock enabled.
> 
> Did this happen after either an update of the OS or Datavyu?

**Comment by Bpepe65** [comment]
It appears that the issue was related to the keyboard, as we switched out the keyboard and it is now working as normal.  Both the "9" key and Data Viewer Controller are now working with the new keyboard.

**Comment by Xubes** [comment]
Awesome—glad it's fixed! Closing this issue.
