### ISSUE TITLE
Open Data button does not show dialog window

### ISSUE THREAD

**Issue by Xubes** [databrary/datavyu#133]
On a Mac computer, when I open Datavyu I am able to open the file I want. However, when I go to "add data", nothing happens. I do not get any error message but no options pop up.

**Comment by Xubes** [comment]
Fixed by updating Datavyu to 1.3.7.

**Comment by lafayettekidslab** [comment]
I'm having this same issue! I have a mac (version 10.13.6) and the latest version of Datavyu. I recently installed it - this is my first time using Datavyu. However, it's not opening the window when I press "add data." Do you have any suggestions?

**Comment by TheoWolf** [comment]
Moved here https://github.com/databrary/datavyu/issues/243
