### ISSUE TITLE
macOS package contains wrong/no version number

### ISSUE THREAD

**Issue by octomike** [databrary/datavyu#137]
**Describe the bug**
The [Info.plist](https://github.com/databrary/datavyu/blob/09d6938d09aac59570c5f6bf366d3786a9facbf4/src/main/deploy/package/macosx/Info.plist#L45) on macos does not contain usable version strings.

**Expected behavior**
`CFBundleVersion` and `CFBundleShortVersionString` should match the Datavyu version.

**Desktop (please complete the following information):**
 - OS: macOS any version

**Additional context**
This is an essential feature for package versioning systems such as [munki](https://github.com/munki/munki/wiki)

**Comment by TheoWolf** [comment]
@octomike Thanks for your input. Indeed, the info.plist is not up to date and doesn't match the current datavyu version, This will  be fixed in the next release (Early next week)
