### ISSUE TITLE
Creating a template spreadsheet

### ISSUE THREAD

**Issue by aligon7** [databrary/datavyu#148]
I am trying to create a template spreadsheet to do all of my coding from. I will be using several coders, and I want a simple way for each of them to be working from the same spreadsheet (i.e., same columns/codes). Is there a simple way to do this?

Thanks!

**Comment by Xubes** [comment]
See this example script if you want to go the scripting route: https://github.com/databrary/Datavyu-Example-Scripts/blob/master/Insert/Insert-Columns.rb
