### ISSUE TITLE
Is it possible to merge two datavyu files into one?

### ISSUE THREAD

**Issue by Xubes** [databrary/datavyu#150]

**Comment by Xubes** [comment]
In Datavyu 1.4.2, there is a function to export and import coding passes from Datavyu files. Use Spreadsheet > Export Passes to JSON to write the columns visible in the current spreadsheet out to a .json file. Then in the file you want to import the columns to, use Spreadsheet > Import Passes from JSON to read the columns from the .json file.

You can also use a script to do this directly between two .opf files or if you need to run this on multiple files at a time. There are two examples on how to transfer columns in our Example Scripts repository: https://github.com/databrary/Datavyu-Example-Scripts/blob/master/Misc/TransferColumns.rb and https://github.com/databrary/Datavyu-Example-Scripts/blob/master/Import/ImportColumns.rb. You can modify the parameters between the ## Parameters and ## Body comments to adapt to your files.

**Comment by Xubes** [comment]
Closing this issue. Feel free to re-open if there is followup.

**Comment by djyle** [comment]
Thanks for this - What if the datavyu files have been made in Datavyu 1.3.7? Is it possible to merge those files?

**Comment by Xubes** [comment]
v1.4.2 should be compatible with files made in 1.3.7—if it's not opening, this could be a bug. Would you be able to share your files? You can zip and upload here or e-mail us at info@datavyu.org.

**Comment by Xubes** [comment]
Closing; re-open if needed.
