### ISSUE TITLE
4x and -4x playback is choppy

### ISSUE THREAD

**Issue by sh0sh1n** [databrary/datavyu#164]
**Describe the bug**
4x and -4x are choppier playback than +/-(8x, 16x, 32x). I imagine this is because of the fake playback. We may want to increase the number of seeks at 4x to have smoother playback.

**Expected behavior**
4x playback should be at least as smooth as 8x and higher playback speeds.

**Comment by TheoWolf** [comment]
Need to reproduce this ticket, not sure if this is in the last released version.

**Comment by sh0sh1n** [comment]
Closing this. I think this is fixed in 1.5.0.
