### ISSUE TITLE
No audio at 1x playback

### ISSUE THREAD

**Issue by Xubes** [databrary/datavyu#168]
**Describe the bug**
No audio.

**To Reproduce**
Add a video using FFMPEG plugin and play.

**Expected behavior**
Audio playback.

**Desktop (please complete the following information):**
 - OS: Windows 7 Pro SP1
 - Datavyu Version 1.5.0rc1

**Comment by TheoWolf** [comment]
@Xubes I tried the audio on both Windows and Mac OSs and there is audio at 1x, Could you please double check your audio settings and let me know if you still have this issue.

**Comment by TheoWolf** [comment]
This is a hardware issue, audio is working as expected at 1x playback.
