### ISSUE TITLE
Disabling Highlight and Focus stops manual focusing

### ISSUE THREAD

**Issue by sh0sh1n** [databrary/datavyu#171]
**Describe the bug**
Disabling Highlight and Focus mode disables the ability to manually focus on cells.

**To Reproduce**
1. Open a spreadsheet with an existing column of cells.
2. Enable Highlight and Focus and play for some time.
3. Disable Highlight and Focus
4. Press the up and down arrow keys to move to other cells in the column.

Selection will move to the other cells but the view won't update to show the other cells if they are out of view.

**Expected behavior**
After Highlight and Focus is disabled, spreadsheet view should still update to show the currently selected cell when the user moves between cells/columns.

**Desktop (please complete the following information):**
 - OS: Windows 7 Pro SP1
 - Datavyu Version 1.5.0rc1

**Additional context**

**Comment by TheoWolf** [comment]
@Xubes Couldn't reproduce this issue, The spreadsheet view update normally after disabling highlight and focus

**Comment by TheoWolf** [comment]
The bug is caused by a conflict between the highlighted and selected cell's state; when a cell is highlighted the associated column is not selected and any shifting between cells will not update the spreadsheet view.

**Comment by TheoWolf** [comment]
@sh0sh1n Cannot reproduce this in Datavyu 1.5.0. Could you please confirm if the issue is still happening in 1.5.0.

**Comment by TheoWolf** [comment]
The bug is not related to the highlighted and focus feature but by how the cell is selected; when clicking on the border of a cell (border highlighted, code and column not selected) moving up and down will not update the view because datavyu cannot find the last selected code in the column where the cell resides.
