### ISSUE TITLE
Adding videos file with no audio crashes the FFmpeg player

### ISSUE THREAD

**Issue by Xubes** [databrary/datavyu#172]
**Describe the bug**
Attempting to add a .avi file using the FFMPEG plugin open the video with the first frame but displays a window with the error message: (null). Playback keys do nothing and the player window does not close. Only solution is to restart Datavyu.

**To Reproduce**
1. Add .avi file using FFMPEG plugin.

A player window opens with the first frame of video. A dialog box opens with an error message (null). No track is added to the Controller.

**Expected behavior**
If FFMPEG plugin cannot play the video file, display an appropriate error message and do not open a player window. If a player window is opened, allow it to be closed.

**Desktop (please complete the following information):**
 - OS: Windows 7 Pro SP1
 - Datavyu Version 1.5.0rc1

**Comment by TheoWolf** [comment]
@Xubes Does the avi file that you tried to load into Datavyu has audio?

**Comment by TheoWolf** [comment]
The following commit in the Datavyu player Repo (https://github.com/databrary/datavyu-ffmpegplugin/pull/142/commits/bc4054a8b7b7a01119936d17cb4e88575804be16) should fix exceptions thrown when video without exception is loaded.

**Comment by Xubes** [comment]
The files did not have audio. Tested with files with audio and FFMPEG opens and plays fine. Noticed one instance where the audio restarted from the beginning when stopping and starting playback, but it was only for that file.

Testing commit next.

**Comment by TheoWolf** [comment]
Issue fixed in Datavyu Player 0.19.
