### ISSUE TITLE
Opening videos with FFMPEG plugin doesn't resize the player window

### ISSUE THREAD

**Issue by sh0sh1n** [databrary/datavyu#173]
**Describe the bug**
When opening a .opf file which had a video added with the JavaFX plugin, there is a prompt to replace the plugin with the default. Clicking yes opens the video and adds it to the track, but the player window is tiny. Once manually resized, the video opens correctly on future opens.

**To Reproduce**
1. Open a Datavyu file associated with a JavaFX video player.
2. Click yes on the dialog box to switch to FFMPEG plugin.

This doesn't happen with all files. Potentially unreproducible.

**Expected behavior**
Videos should always open with either persistent window size information or default resolution. This is a minor inconvenience since the user can manually resize the player window. May be difficult for new users to find the player window since it is so small.

**Desktop (please complete the following information):**
 - OS: Windows 7 Pro SP1
 - Datavyu Version 1.5.0rc1

**Comment by TheoWolf** [comment]
@Xubes Cannot reproduce this bug, if you could share files that are causing the problem

**Comment by TheoWolf** [comment]
@sh0sh1n Please test this ticket with RC4, It got fixed when switching to SDL player. Issue closed.
