### ISSUE TITLE
MPV plugin does not load

### ISSUE THREAD

**Issue by Xubes** [databrary/datavyu#174]
**Describe the bug**
Attempting to open a video using the MPV plugin fails and displays error message.

**To Reproduce**
1. Ad video using MPV plugin

**Expected behavior**
MPV plugin should open the video (especially .mp4).

**Screenshots**
![mpv_error](https://user-images.githubusercontent.com/1036484/52767037-2b379000-2ff7-11e9-9267-3fb80c98f6c5.png)

**Desktop (please complete the following information):**
 - OS: Windows 7 Pro SP1
 - Datavyu Version 1.5.0rc1

**Comment by TheoWolf** [comment]
Not relevant, since the MPV player will be excluded from the 1.5.0 release. I will close this ticket.
