### ISSUE TITLE
FFMPEG opens video at third frame.

### ISSUE THREAD

**Issue by Xubes** [databrary/datavyu#189]
**Describe the bug**
Opening Counter1080.mp4 using FFMPEG initializes the player at frame 2. NativeOSX opens at frame 0. Seeking to timestamp 0 moves the FFMPEG frame to frame zero.

**To Reproduce**
1. Add frame counter video.

**Expected behavior**
Video opens at frame 0. Jogs move through successive frames (or the frames associated with each time increment).

**Screenshots**
<img width="1124" alt="screen shot 2019-03-06 at 4 54 01 pm" src="https://user-images.githubusercontent.com/1036484/53916633-98f03e00-4030-11e9-812f-78a03864304c.png">

**Version (please complete the following information):**
 - OS: OS X Sierra
- Datavyu: 1.5.0rc1b

**Additional context**
Jogging behavior is weird for both the NativeOSX and FFMPEG plugins. For instance, NativeOSX does not show frame 2.

**Comment by Xubes** [comment]
This is not an issue on Windows. FFMPEG plugin on Windows 7 opens at frame 0.

**Comment by TheoWolf** [comment]
@Xubes This issue seems to be fixed but will need extensive testing before closing this ticket

**Comment by TheoWolf** [comment]
This issue is fixed in this PR (https://github.com/databrary/datavyu-ffmpegplugin/pull/155)
