### ISSUE TITLE
FFMPEG and NativeOSX display different frames for same time

### ISSUE THREAD

**Issue by Xubes** [databrary/datavyu#190]
**Describe the bug**
In general, FFMPEG is one frame ahead of NativeOSX. At the beginning and end of videos, jogging behavior is erratic.

For example, adding a video using FFMPEG and NativeOSX and jogging forward displays the following frame sequences:

| Jog | NativeOSX | FFMPEG |
|-----|-----------|--------|
| 0   | 0         | 2      |
| 1   | 0         | 2      |
| 2   | 1         | 3      |
| 3   | 2,3*      | 4      |
| 4   | 4         | 5      |

* For jog 3, NativeOSX shows frame 2 then quickly replaces it with frame 3.

**To Reproduce**
1. Add frame counter video with both plugins
2. Jog forward

**Expected behavior**
Open at frame zero, jogs advance by one frame.

**Desktop (please complete the following information):**
 - OS: OS X Sierra
 - Datavyu Version 1.5.0rc1b

Related to #189

**Comment by TheoWolf** [comment]
@Xubes The bug is fixed for the FFmpeg plugin by seeking to a frame index. However, the Native OSX is a little bit complex to solve; because of seeking accuracy, the only workaround is to clamp the NativeOSX stream duration and force it to start at 10 ms instead of 0 ms.
