### ISSUE TITLE
FFMPEG jog and seek do not work

### ISSUE THREAD

**Issue by Xubes** [databrary/datavyu#193]
**Describe the bug**
Jogging does not advance the frame. It will either not show a new frame or move to a random frame and cycle back on the next jog.

Seeking to previously coded points in the frame counter video does not seek correctly. The frames shown are vastly different from the coded frames.

**To Reproduce**
1. Add frame counter video.
2. Jog forwards and backwards
3. Seek to cells in the Counter.opf file.

**Expected behavior**
Advance frames through video.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win7 SP1
 - Datavyu Version 1.5.0rc1b

**Additional context**

**Comment by Xubes** [comment]
Normal playback (1x speed) also breaks after seeking.

**Comment by Xubes** [comment]
Verified jog does not work on Win10 (1803). However, playback functions (all speeds) are working as expected.

**Comment by TheoWolf** [comment]
@Xubes This is a bug in the JavaFX plugin and previous version of Datavyu (1.4.0, 1.3.7 ...) Datavyu was putting a default value of 30 FPS when the plugin can't get the FPS from the video headers, and that default value is never persisted in the OPF File. Instead, Datavyu was assigning a -1 as a value to the FPS field.

**Comment by TheoWolf** [comment]
@Xubes I will do further testing on Windows Platform tomorrow
