### ISSUE TITLE
How to script: time of specific code

### ISSUE THREAD

**Issue by ars17psu** [databrary/datavyu#212]
I have some coded data and haven't done ruby scripting for quite some time. Is there sample code available for summing the time of a specific code in a column within a single .opf file and/or across .opf files?

Thank you.

**Comment by Xubes** [comment]
@ars17psu We generally recommend users use an export script to export the raw coded data and then aggregate using something like SPSS or R. However, if you still want to be able to do this using a script, I've added an example script to count the frequencies and durations of code values: https://github.com/databrary/Datavyu-Example-Scripts/blob/master/Export/export_freqs_durs.rb

You can modify it to accumulate the data over multiple files and write it out to a csv.

**Comment by ars17psu** [comment]
Thank you Shohan!

Andrea
