### ISSUE TITLE
Transition to 1x playback has large delay

### ISSUE THREAD

**Issue by Xubes** [databrary/datavyu#216]
**Describe the bug**
When playing at 2x, if I press the play button or shuttle back key to go to 1x playback speed, there is a long delay before playback transitions to 1x speed. Playback continues at 2x speed during this delay. This does not happen at 4x and to a slight extent at 16x and 32x (but I think that may be a performance issue rather than a bug).

This also happens moving from 1/2x to 1x.

**To Reproduce**
1. Add a video with NativeOSX plugin.
2. Play at 2x speed.
3. Change playback to 1x speed either through Numpad-8 or Numpad-4.

1. Play video at 1x speed.
2. Shuttle down to 1/2x speed and play for a few seconds.
3. Shuttle forward to 1x speed.

**Expected behavior**
Near instantaneous transition to 1x speed.

**Desktop (please complete the following information):**
 - OS: OS X 10.13.6
 - Datavyu: 1.5.0rc2, 1.5.0rc3
 - Plugin: NativeOSX

**Comment by Xubes** [comment]
Updated with additional information from rc3 testing.

**Comment by TheoWolf** [comment]
Fixed in FFmeg plugin 0.21 (https://github.com/databrary/datavyu-ffmpegplugin/issues/172)
