### ISSUE TITLE
Transition from 4x to 2x sometimes causes jumping

### ISSUE THREAD

**Issue by Xubes** [databrary/datavyu#217]
**Describe the bug**
Playing at 4x speed and higher and then transitioning to 2x speed causes the player to jump frequently during the 2x playback.

**To Reproduce**
1. Play at 1x
2. Shuttle to 2x
3. Shuttle to 4x, play for ~5 seconds
4. Shuttle to 8x, play for ~5 seconds
5. Shuttle to 4x, play for ~5 seconds
6. Shuttle to 2x

**Expected behavior**
2x playback without jumps.

**Desktop (please complete the following information):**
 - OS: OSX 10.13.6
 - Datavyu: 1.5.0rc2

**Comment by TheoWolf** [comment]
Fixed in FFmeg plugin 0.21 (https://github.com/databrary/datavyu-ffmpegplugin/issues/172)
