### ISSUE TITLE
4x playback has choppy audio

### ISSUE THREAD

**Issue by sh0sh1n** [databrary/datavyu#219]
**Describe the bug**
4x playback has choppy/unhelpful audio, no audio is expected.

**To Reproduce**
1. Play at 4x speed

**Expected behavior**
No audio, or sped up audio if possible.

**Desktop (please complete the following information):**
 - OS: OSX 10.13.6
 - Datavyu: 1.5.0rc2

**Comment by TheoWolf** [comment]
The behavior is how the AVFoundation native player works, the Native OSX player will be deprecated in future releases and doesn't need to be maintained anymore. The only workaround that we can do is to use the fake playback for playback speeds >= 4x

**Comment by TheoWolf** [comment]
Closing this ticket
