### ISSUE TITLE
Copy onset/offset across multiple columns

### ISSUE THREAD

**Issue by melrob1119** [databrary/datavyu#222]
Hello,

New user here. I am interested in setting up my data so that speaking turns are first coded in one column (M or P with onset and offset), and that the other columns are exactly aligned to the speaking turns. For example, I want one code identifying speaker, and another code transcribing what the speaker said during that turn. Is it possible to copy the onset/offset of the speaking turn to other columns?

Thanks for any help you can provide!

**Comment by Xubes** [comment]
Yep, it's fairly straightforward to do this in a script. Let's say your speaker column was called "Speaker", and you wanted to copy over all the cells to a new column column called "Transcription", you could use the following code:

```ruby

require 'Datavyu_API.rb'

col = get_column('Speaker')
ncol = new_column('Transcription', 'transcript')
col.cells.each do |cell|
  ncell = ncol.new_cell
  ncell.onset = cell.onset
  ncell.offset = cell.offset
end
set_column(ncol)
```
If you wanted to preserve space, you could also just add a new code to the existing column which identified the speaker and go through all the cells to fill in the transcription. For example:
```ruby
require 'Datavyu_API.rb'
col = get_column('Speaker')
col.add_code('transcript')
set_column(col)
```

There's also a script available if you need to do more complicated copying: https://github.com/databrary/Datavyu-Example-Scripts/blob/master/Insert/Insert-SecondaryCodingPass.rb
It's set up to allow you to edit the variables in the parameter section (before the ## Body line) to control what gets copied where.

**Comment by Xubes** [comment]
Closing this issue. Re-open if needed.

**Comment by melrob1119** [comment]
Thank you!

--
Melissa Mitchell Robertson, PhD
Postdoctoral Research Associate
Industrial-Organizational Psychology
Owens Institute of Behavioral Research
University of Georgia
