### ISSUE TITLE
Startup crash when there is no Internet connection

### ISSUE THREAD

**Issue by sh0sh1n** [databrary/datavyu#226]
**Describe the bug**
Datavyu on Windows fails to start up after a clean install if there is no active Internet connection.

**To Reproduce**
1. Install Datavyu
2. Disable network connections
3. Launch Datavyu

**Expected behavior**
Datavyu should launch regardless of network availability.

**Desktop (please complete the following information):**
 - OS: Windows
 - Datavyu version 1.4.2

**Comment by TheoWolf** [comment]
Duplicate #242
