### ISSUE TITLE
Transitioning from 8x to 2x playback breaks performance

### ISSUE THREAD

**Issue by Xubes** [databrary/datavyu#230]
**Describe the bug**
Playing a video at 8x speed and then shuttling down to 2x speed causes stuttering every 1-2 seconds (like a resync).

**To Reproduce**
1. Play a video and shuttle up to 8x speed
2. Shuttle down to 2x speed

**Expected behavior**
2x playback without stuttering/resyncing

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OSX
 - Version: 1.5.0rc3
 - Plugin: NativeOSX

**Comment by Xubes** [comment]
This also happens when going from -8x to -1x.

**Comment by TheoWolf** [comment]
Fixed in FFmeg plugin 0.21 (https://github.com/databrary/datavyu-ffmpegplugin/issues/172)
