### ISSUE TITLE
Playback frozen at negative playback speeds

### ISSUE THREAD

**Issue by Xubes** [databrary/datavyu#231]
**Describe the bug**
Shuttling down from -32x playback speed to -2x or -1x freezes the video player for a while (>10s).

**To Reproduce**
1. Shuttle from 0x to -32x gradually (1-2s between shuttles).
2. Shuttle from -32x to -2x or -1x, gradually.

**Expected behavior**
Quick transition to different playback speed. Or an indicator to show that the video is loading/processing.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac 10.14.4
 - Version: 1.5.0rc3
 - Plugin: OSXNative

**Comment by TheoWolf** [comment]
Fixed in FFmeg plugin 0.21 (https://github.com/databrary/datavyu-ffmpegplugin/issues/172)
