### ISSUE TITLE
Backwards playback higher than -1x does not work on Windows

### ISSUE THREAD

**Issue by sh0sh1n** [databrary/datavyu#233]
**Describe the bug**
On Windows, backwards playback -2x and higher cause the video player to freeze.

**To Reproduce**
1. Add video and shuttle to -2x playback speed.

**Expected behavior**
-2x should work as expected (works on Mac).

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Datavyu version 1.5.0rc3
 - Plugin: FFMPEG

**Comment by TheoWolf** [comment]
This ticket seems to be fixed in 1.5.0-rc4 release. I Will keep it here for more testing.

**Comment by sh0sh1n** [comment]
Works in new binary. Closing.
