### ISSUE TITLE
Offset time not appearing in cell

### ISSUE THREAD

**Issue by aligon7** [databrary/datavyu#240]
As I am coding, if I add a new cell the onset time is indicated, but the offset time is not indicated. I've watched the example videos and it seems the offset time should be specified once I add a new cell or click out of that cell. Am I doing something wrong? Please let me know if you have any tips for getting the onset time specified within the cell.

Thanks!

**Comment by Xubes** [comment]
Which key are you using to insert new cells? There are three numpad keys which create new cells in the spreadsheet: Enter, 0 (Numpad-Zero), and = (Numpad-Equal). The enter key is the simplest—it inserts a cell and sets the onset time to the current time in the Controller. 

The zero key does the same, but in addition it sets the offset of the previous cell which was inserted to one millisecond before the current time. This is used in what we call "continuous coding" where there is no time gap between cells in a coding region.

The equals key inserts a new cell and sets both its onset and offset times to the current Controller time. AFAIK, clicking outside of a cell won't update a timestamp.

**Comment by Xubes** [comment]
Closing this issue. Feel free to re-open if needed.
