### ISSUE TITLE
Backwards playback stutters

### ISSUE THREAD

**Issue by sh0sh1n** [databrary/datavyu#241]
**Describe the bug**
All backwards playback speeds stutter.

**To Reproduce**
1. Add video
2. Play back at negative playback speed

**Expected behavior**
Backwards playback without stuttering

**Desktop (please complete the following information):**
 - OS: OSX 10.13.6 (High Sierra)
 - Datavyu version 1.5.0rc4

**Additional context**
Terminal output shows lots of error messages similar to:

> co located POCs unavailable

**Comment by TheoWolf** [comment]
Duplicate #234
