### ISSUE TITLE
I can't open the Add Data window on my Mac? 

### ISSUE THREAD

**Issue by lafayettekidslab** [databrary/datavyu#243]
I recently downloaded the latest version of Datavyu on Mac (version 10.13.6) - I'm excited to start using it! I've opened it and I have a video file I'd like to look at. It's in a QuickTime format. However, when I press "add data" on the controller, nothing is happening. No window pops up and I don't have an option to open the file. Can you help me fix it? Thanks!

**Comment by TheoWolf** [comment]
Hello @lafayettekidslab,

Welcome to the Datavyu community and we are sorry that you are facing issues with Datavyu.
Some suggestions to help you overcome your problem:
- Install Datavyu 1.3.7 version www.datavyu.org (1.4.0 is still in Development)
- Make sure to copy datavyu.app to your Application folder. 
Please let me know if it fixed your problem.

**Comment by Xubes** [comment]
If you continue to have issues, send an e-mail to info@datavyu.org to troubleshoot further.

**Comment by lafayettekidslab** [comment]
Hi!
Thanks so much! Those steps are already taken care of. Please let me know
what to try next! Right now, I can open the Datvyu application, but when I
press "add data" nothing happens. No window pops up, so I'm not able to
select the video file I'm trying to open.
Thank you,
Erin
---
The Lafayette Kids Lab
under the direction of Lauren J. Myers, Ph.D. in the Lafayette College
Department of Psychology
EXCEL scholar research assistants: Erin McKenney (class of 2020)

web: http://sites.lafayette.edu/kidslab/
social: https://www.facebook.com/lafayettekidslab
e-mail: lafayettekidslab@gmail.com
phone: (610) 330-5870

**Comment by TheoWolf** [comment]
Please send an email to info@datavyu.org someone will get in touch with you ASAP
