### ISSUE TITLE
Can't load video: library error

### ISSUE THREAD

**Issue by sh0sh1n** [databrary/datavyu#244]
**Describe the bug**
Trying to add a .mp4 video with the FFMPEG plugin gives error message.

**To Reproduce**
1. Add Data and select a video

**Expected behavior**
Load and prepare video for playback.

**Screenshots**
<img width="623" alt="Screen Shot 2019-06-20 at 3 54 07 PM" src="https://user-images.githubusercontent.com/1036484/59877519-09b72e00-9374-11e9-9ad3-13f3733aa821.png">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Datavyu version 1.5.0rc4

**Comment by TheoWolf** [comment]
@Xubes It is working on my PC, I will double check it, maybe I uploaded the wrong binary.

**Comment by TheoWolf** [comment]
It is working on my end.

**Comment by Xubes** [comment]
Still getting this using Windows 10 VirtualBox VM. Will test on non-VM.

**Comment by sh0sh1n** [comment]
I tried this again on a Win10 installation and it gives the same error.

**Comment by TheoWolf** [comment]
@sh0sh1n Bundled 1.5.0-RC4 with Release Configuration. The version that was causing issues on Windows was bundled with Debug Configuration which requires .NET framework and SDK installed on the machine.
I will close this ticket.
