### ISSUE TITLE
Playing at 4x breaks 2x playback

### ISSUE THREAD

**Issue by sh0sh1n** [databrary/datavyu#247]
**Describe the bug**
Shuttling forward to 4x degrades performance. Shuttling back to 2x does not play the video at 2x speed—it continues to jump from frame to frame. However, audio plays at 2x speed.

**To Reproduce**
1. Shuttle forward to 4x
2. Shuttle back to 2x

**Expected behavior**
Playback should continue at 2x speed.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Datavyu version 1.5.0rc4

**Comment by TheoWolf** [comment]
@sh0sh1n doesn't seem to happen on my machine this will require testing it on slower machines.

**Comment by TheoWolf** [comment]
Tested on a VM with low specs and cannot reproduce this behavior.

**Comment by sh0sh1n** [comment]
Confirmed not present in new binary. Closing.
