### ISSUE TITLE
Holding down jog key freezes app

### ISSUE THREAD

**Issue by sh0sh1n** [databrary/datavyu#248]
**Describe the bug**
Holding down the jog forward key freezes Datavyu.

**To Reproduce**
1. Play
2. Stop
3. Hold down jog forward key
4. Repeat 1-3 as needed

**Expected behavior**
Jog forward as quickly as possible while the jog forward key is held down.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Datavyu version 1.5.0rc4

**Comment by TheoWolf** [comment]
This is because of jogging by frame feature, we will need to roll back to jogging by time.

**Comment by TheoWolf** [comment]
Fixed in FFmpeg plugin version 0.22 (PR: https://github.com/databrary/datavyu-ffmpegplugin/pull/185)

**Comment by sh0sh1n** [comment]
Noticing this again in rc4. It doesn't happen always, but occasionally happens while jogging. More prevalent with multiple videos open.

**Comment by TheoWolf** [comment]
The fix is already merged in the dev branch you can try it there. It will be available in RC5

**Comment by sh0sh1n** [comment]
Got it. I'll close it for now then and check again in rc5.

**Comment by TheoWolf** [comment]
@sh0sh1n Please Check if this bug is fixed in RC5

**Comment by TheoWolf** [comment]
@sh0sh1n Can we close this issue?

**Comment by sh0sh1n** [comment]
Yes.
