### ISSUE TITLE
Mouse does not show above player window

### ISSUE THREAD

**Issue by sh0sh1n** [databrary/datavyu#249]
**Describe the bug**
The FFMPEG plugin window causes the mouse cursor to disappear when entering the window.

**To Reproduce**
1. Open video using FFMPEG plugin
2. Move mouse cursor over the player window

**Expected behavior**
Mouse cursor should stay above the player window

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Datavyu version 1.5.0rc4

**Comment by TheoWolf** [comment]
Fixed here: https://github.com/databrary/datavyu-ffmpegplugin/issues/189
