### ISSUE TITLE
Backwards playback does not work

### ISSUE THREAD

**Issue by sh0sh1n** [databrary/datavyu#253]
**Describe the bug**
Backwards playback does not work.

**To Reproduce**
1. Shuttle to any backwards speed.

**Expected behavior**
Backwards playback at -1x should work.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Datavyu version 1.5.0rc4

**Additional context**
Duplicates #194

**Comment by TheoWolf** [comment]
We tested it with @sh0sh1n on my PC and the backward playback was working as expected.

**Comment by TheoWolf** [comment]
Tried on a VM with 2Gb of Ram and 2 CPU cores enabled and it is working.

**Comment by sh0sh1n** [comment]
Retested with new binary and works as anticipated. Slow backwards playback (-1/2x to -1/32x) has odd behavior: the video jumps back a frame and plays forward, producing a stuttering effect. May need to address this in a future update.
