### ISSUE TITLE
Datavyu v1.3.7 not opening on Mac

### ISSUE THREAD

**Issue by amwoodward13** [databrary/datavyu#254]
**Describe the bug**
I can no longer open Datavyu v1.3.7 on any of the Macs in our lab. Whenever we try to open the app, the icon appears in the Menu bar, bounces twice, and disappears. No Windows appear. We tried uninstalling, reinstalling, and running on other computers, but Datavyu will not open. 

**To Reproduce**
1. Go to "Open Datavyu in Finder" 
2. Click on Datavyu Icon
3. See error doesn't open

**Expected behavior**
We expected the program to open.

**Screenshots**
N/A 
**Desktop (please complete the following information):**
 - OS: Mac
 - Datavyu version 1.3.7

**Additional context**

**Comment by sh0sh1n** [comment]
Could you try deleting the Datavyu folder inside "~/Library/Application Support/"? You can get to the Library folder using the CMD+SHIFT+L shortcut in Finder. You can also access it from the Go menu in Finder if you hold down the Option key. See: https://www.lifewire.com/os-x-is-hiding-your-library-folder-2260833

**Comment by amwoodward13** [comment]
Hi! 
I deleted the Datavyu folder inside the Application Support folder in the library. However, it did not fix the problem. Thanks for your help!

**Comment by sh0sh1n** [comment]
Do you have time to troubleshoot? Please follow up with an e-mail to info@datavyu.org

**Comment by sh0sh1n** [comment]
This was due to Yosemite no longer being supported. Closing this.
