### ISSUE TITLE
Controller freezes when playing multiple videos

### ISSUE THREAD

**Issue by sh0sh1n** [databrary/datavyu#263]
**Describe the bug**
Probably related to #248 . During normal use (play, shuttling, or jogging). The Controller freezes and the application needs to be forced to quit.

**To Reproduce**
1. Add two or more videos
2. Use Datavyu to play, shuttle, and jog. There seems to be no pattern as to when or how the freeze appears.

**Expected behavior**
Datavyu should not freeze.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Datavyu version 1.5.0rc4

**Additional context**

**Comment by TheoWolf** [comment]
It is probably related to #248, I will label it as need more info so we can test it in RC5

**Comment by TheoWolf** [comment]
@sh0sh1n Please confirm that this bug is fixed in RC5.

**Comment by TheoWolf** [comment]
@sh0sh1n Can we close this issue?

**Comment by sh0sh1n** [comment]
Not present in rc5.
