### ISSUE TITLE
Datavyu Scripting NoMethoderror

### ISSUE THREAD

**Issue by wuoituw** [databrary/datavyu#265]
Hello!
I'm trying to learn how to code in datavyu and I keep getting the following error no matter what I do.
It's just a simple script to copy the data from one column to another.

*************************
Running Script: CopyColumn1.rb on project: datavyu001
*************************
NoMethodError: undefined method `chr' for nil:NilClass
   set_cells at filepath/Datavyu_API.rb:360
        each at org/jruby/RubyArray.java:1613
   set_cells at filepath/Datavyu_API.rb:357
  get_column at filepath/Datavyu_API.rb:751
      (root) at <script>:4

***** SCRIPT ERROR *****

NoMethodError: undefined method `chr' for nil:NilClass
   set_cells at filepath/Datavyu_API.rb:360
        each at org/jruby/RubyArray.java:1613
   set_cells at filepath/Datavyu_API.rb:357
  get_column at filepath/Datavyu_API.rb:751
      (root) at <script>:4

See line 4 of filepath\CopyColumn1.rb:
	fill = get_column("fill");
*************************

I've only got a bit of experience in c++ coding but I can't get past this error message.

Any help would be greatly appreciated!

W

**Comment by sh0sh1n** [comment]
I have a feeling this is due to the codes inside the "fill" column. Can you check the file and make sure the Code Editor displays names for all of the codes?

**Comment by wuoituw** [comment]
The Code Editor displays a bunch of names in the same format:
fill(<>)
false_a(<>)
false_b(<>)
etc.

Is this what it is supposed to look like?
Thus far I've only used it to note down some times.

**Comment by sh0sh1n** [comment]
Adding a note here: this is most likely triggered by the automatic code name sanitization in the API:

```ruby
      if ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"].include?(arg[0].chr)
        arg = "_" + arg
      end
```

We can make that code a lot better. IIRC, there's a sanitize routine in the RColumn class that we could use throughout the API.

**Comment by sh0sh1n** [comment]
@wuoituw Yes, this is definitely due to not having names for the codes. Can you put a letter inside the "<>"? Datavyu currently accepts empty code names but it causes issues with the Ruby API. One or the other needs to be updated—but the quickest workaround is to just give each column a valid code name.

**Comment by wuoituw** [comment]
Awesome, that worked! Thank you!

**Comment by sh0sh1n** [comment]
Nice. I've created a new issue to have this resolved in a future release. See #266
