### ISSUE TITLE
Saved plugins not consistent between versions

### ISSUE THREAD

**Issue by sh0sh1n** [databrary/datavyu#273]
**Describe the bug**
Datavyu files saved with an older version of Datavyu (tested using v1.3.7) which have videos added with NativeOSX plugin open in Datavyu 1.5.0 as FFMPEG (with warning message saying the plugin it was saved with is no long supported).

Datavyu files saved with v1.5.0 with FFMPEG videos open in v1.3.7 as NativeOSX (no FFMPEG plugin present).

**To Reproduce**
1. Use version 1.3.7 to add a video to a project using the NativeOSX plugin.
2. Save the file.
3. Open the file in version 1.5.0

**Expected behavior**
Videos opened previously with NativeOSX should still open in NativeOSX.

**Desktop (please complete the following information):**
 - OS: macOS
 - Datavyu version 1.5.0rc5

**Comment by TheoWolf** [comment]
Closing this, duplicate #305
