### ISSUE TITLE
Phantom video window

### ISSUE THREAD

**Issue by sh0sh1n** [databrary/datavyu#275]
**Describe the bug**
Datavyu creates a blank phantom window in the upper-left corner of the screen. When this window is selected, playback keys work as expected in the main window. Closing this window removes it for the session but re-appears when the file is opened again, even if you save after closing the phantom window.

**To Reproduce**
1. Add a video to a project.
2. Save the file.
3. Open the file

**Expected behavior**
No phantom window.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 10.13.6
 - Datavyu version 1.5.0rc5

**Additional context**

**Comment by TheoWolf** [comment]
@sh0sh1n Could you please specify the plugin.
