### ISSUE TITLE
Tracks resize window icon does not work

### ISSUE THREAD

**Issue by sh0sh1n** [databrary/datavyu#276]
**Describe the bug**
The zoom icon on Controller tracks does not resize the video to the selected size. No effect is visible.

**To Reproduce**
1. Add a video
2. Use the zoom icon to resize video to preset size

**Expected behavior**
Respective playback window is scaled to selected size.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 13.6
 - Datavyu version 1.5.0rc5

**Additional context**

**Comment by TheoWolf** [comment]
@sh0sh1n Please tag the plugin.

**Comment by sh0sh1n** [comment]
Also broken on Windows

**Comment by TheoWolf** [comment]
Fixed in https://github.com/databrary/datavyu-ffmpegplugin/issues/191
