### ISSUE TITLE
Backwards playback does not work

### ISSUE THREAD

**Issue by sh0sh1n** [databrary/datavyu#277]
**Describe the bug**
All backwards playback speeds move the needle and the Controller time appropriately, but the video player plays at forward normal (1x) speed.

**To Reproduce**
1. Add video and jump to somewhere in the middle of the video
2. Shuttle to backwards playback speeds

**Expected behavior**
Backwards playback at appropriate speed

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Datavyu version 1.5.0rc5

**Additional context**
See also #194 #253

**Comment by TheoWolf** [comment]
@sh0sh1n Does the Videos controller seek backward? I cannot reproduce the problem, could you please share the video that you are having problems with?
