### ISSUE TITLE
Jump back key with player window focused

### ISSUE THREAD

**Issue by sh0sh1n** [databrary/datavyu#278]
**Is your feature request related to a problem? Please describe.**
The jump back key does not work if the video player window is selected. All the other keys work with the player focused, so there's no reason not to have this work as well.

**Describe the solution you'd like**
Jump back function works as expected if the video player is focused.

**Comment by TheoWolf** [comment]
Fixed in https://github.com/databrary/datavyu-ffmpegplugin/issues/194
