### ISSUE TITLE
Dragging track past needle does not seek to last frame

### ISSUE THREAD

**Issue by sh0sh1n** [databrary/datavyu#279]
**Describe the bug**
Moving a video track left past the needle should seek to last frame

**To Reproduce**
1. Add video and seek to somewhere in the middle
2. Drag the track left past the needle

**Expected behavior**
Video window seeks to last frame. Currently seeks somewhere near the end.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Datavyu version 1.5.0rc5

**Comment by TheoWolf** [comment]
Fixed in FFmpeg-plugin 0.22, PR: https://github.com/databrary/datavyu-ffmpegplugin/pull/210
