### ISSUE TITLE
Highlight and focus does not maintain selected code

### ISSUE THREAD

**Issue by sh0sh1n** [databrary/datavyu#280]
**Describe the bug**
In Highlight and Focus mode, when focus moves to a different cell, the selected code switches to the first code in the cell.

**To Reproduce**
1. Enable highlight and focus mode
2. Select a cell in a column with existing cells. Select any code besides the first code
3. Play the video

**Expected behavior**
The same code should remain focused/selected when moving to a new cell.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Datavyu version 1.5.0rc5

**Additional context**

**Comment by TheoWolf** [comment]
@sh0sh1n The current implementation of the highlight and focus is as follow:
* When the focus moves to a different cell the first empty code will be selected.
* if there is no empty code in the cell the focus will be requested on the cell (and select the first code)

Please confirm that you want to select the same code (Code position) when moving to a new cell and there is no empty code in the cell.

**Comment by sh0sh1n** [comment]
@TheoWolf Yep. The focus moving to the first code only makes sense in Quick Key Mode.
