### ISSUE TITLE
FFMPEG does not seek to last frame of video

### ISSUE THREAD

**Issue by sh0sh1n** [databrary/datavyu#281]
**Describe the bug**
The frame counter test video will play until frame 8991 (00:05:00:074). However, if a cell is created at the very last frame, FFMPEG fails to seek to it.

**To Reproduce**
1. Add frame counter video and drag needle to end of video
2. Insert point cell at end of video
3. Drag needle back
4. Seek to the point cell

**Expected behavior**
Seek to last frame of the video.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Datavyu version 1.5.0rc5

**Additional context**
This was observed before, but I never tested to see if the video played to the last frame. This may be due to encoding settings. Need to test with constant frame rate video.

**Comment by TheoWolf** [comment]
Related to #279

**Comment by TheoWolf** [comment]
Fixed in https://github.com/databrary/datavyu-ffmpegplugin/pull/210
