### ISSUE TITLE
Datavyu scripts won't run

### ISSUE THREAD

**Issue by sh0sh1n** [databrary/datavyu#285]
**Describe the bug**
Scripts crash.

**To Reproduce**
1. Run a script with: require 'Datavyu_API.rb'; puts get_datavyu_version

**Expected behavior**
API should load without errors

**Screenshots**
<img width="1331" alt="Screen Shot 2019-07-26 at 4 36 13 PM" src="https://user-images.githubusercontent.com/1036484/61980295-51a92080-afc4-11e9-8c88-19b28ee0a6b3.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.14.4
 - Datavyu version 1.5.0

**Additional context**
*************************
Running Script: test.rb on project: (untitled)
*************************
NameError: cannot link Java class org.datavyu.util.DatavyuVersion (java.lang.NoClassDefFoundError: Could not initialize class org.datavyu.util.DatavyuVersion)
       method_missing at org/jruby/javasupport/JavaPackage.java:259
  get_datavyu_version at uri:classloader:/Datavyu_API.rb:2663
               <main> at <script>:3

***** SCRIPT ERROR *****

NameError: cannot link Java class org.datavyu.util.DatavyuVersion (java.lang.NoClassDefFoundError: Could not initialize class org.datavyu.util.DatavyuVersion)
       method_missing at org/jruby/javasupport/JavaPackage.java:259
  get_datavyu_version at uri:classloader:/Datavyu_API.rb:2663
               <main> at <script>:3

See line 3 of /Users/shohanhasan/Desktop/!Workspaces2019/Jul26/test.rb:
puts get_datavyu_version
*************************

**Comment by sh0sh1n** [comment]
@TheoWolf Did this get resolved? Can't reproduce anymore.

**Comment by TheoWolf** [comment]
@sh0sh1n This problem happened to me, I suspect the issue is related to the IDE and not the Source Code. Please, don't close it, I would like to investigate it further

**Comment by TheoWolf** [comment]
This is due to an exception thrown in a static block when using datavyu offline.

**Comment by TheoWolf** [comment]
Fixed in https://github.com/databrary/datavyu/pull/321/commits/ac45a081fb26762cc7d4f558ec188ffb797cf881
