### ISSUE TITLE
NativeOSX player backward compatibility with Datavyu 1.3.7

### ISSUE THREAD

**Issue by TheoWolf** [databrary/datavyu#305]

**Comment by sh0sh1n** [comment]
This is still a problem. See these two project settings files which are NOT interchangeable (output is `diff -y`). Suggestion is to add a plugin_id field in addition to the name and treat it with higher precedence than the plugin name, rather than replacing the name with the uuid.



[project_diff.txt](https://github.com/databrary/datavyu/files/3774317/project_diff.txt)

**Comment by TheoWolf** [comment]
@sh0sh1n Having UUID and plugin class names won't make sense, because the goal of having a UUID is to not depend on a class name that could be refactored at any time. we knew that this will have backward compatibilities issues but all that we can do is to map old plugin class names to the appropriate plugin and users will have to update there OPF files, we took this decision a long time ago.
Having both will just be redundant and will add unnecessary logic if the problem is in Ruby script ve maybe this should be fixed in the ruby API by calling the appropriate Java method that will get you the plugin, this ticket is just for 1.3.7 OPF files coded with Native OSX plugin which the name is different from the 1.5.0 version

**Comment by TheoWolf** [comment]
@sh0sh1n Just for information, Datavyu doesn't fully rely on UUIDs, plugin manager and plugins are still using class names. The UUID (Fixed) is just used to get the name of the class (that could change between versions). So, if the ruby API should not rely on UUID but only use it to find the plugin name associated with it.

**Comment by TheoWolf** [comment]
Note that must be added to www:
Video Controller Settings for projects opened or created in Datavyu >=1.5.0 versions are not compatible with previous versions. You can still use an older Datavyu version and reload the video.
