### ISSUE TITLE
datavyu 1.51 and java script

### ISSUE THREAD

**Issue by johnerichards** [databrary/datavyu#310]
I just installed 1.5.1 and am trying to run a script from a prior version. I get the error

NameError: missing class name (`org.datavyu.controllers.ExportDatabaseFileC')
  method_missing at org/jruby/javasupport/JavaPackage.java:259
          <main> at <script>:1

Does this mean that java is not supported on 1.5.1?

**Comment by johnerichards** [comment]
I understand now that this is not necessarily a lack of java, but can't call the java support package.

I found the example rb script that simulates the export-to-csv.  I have a question about using scripts.  Can I call an outside script within a rb script with parameters?  e.g., have the export_csv.rb in a folder like a script library, call the script with the input filename and outputfilename, and then run the external script from the rb script?  I can think of other ways to do this (e.g., load the db, run the script function to just create the data, then open the output file and put the data, eg.

$db,$pj = load_db("inputdata.opf")
outputdatastrring=createcsv.rb
outfile=open("outputfile.csv","w+")
outfile.puts data.string
outfile.close

**Comment by TheoWolf** [comment]
@jperricone Can you please check this issue.

**Comment by jperricone** [comment]
I am finding that you can run outside rb scripts by specifying the full path and using the load function in Ruby: 

fpath = File.expand_path('~/Desktop')
f = File.join(fpath,'change_code.rb')
load f

When I run this .rb file, it runs change_code.rb on the currently open spreadsheet. Does this answer your question?

Thanks,
Joey
