### ISSUE TITLE
How to run a script on multiple files at once?

### ISSUE THREAD

**Issue by ychen189** [databrary/datavyu#315]
I'm trying to add a column and its corresponding codes to a bunch of Datavyu files. Is there a way to add a line to the "add column" script so that it runs on all of them at once?

**Comment by jperricone** [comment]
I would recommend using the RunBatch.rb function. You can point it to a specific script (that runs on a currently opened spreadsheet), and then a folder of .opf files. It will automatically run the script on each file. 
https://github.com/databrary/Datavyu-Example-Scripts/blob/master/Misc/RunBatch.rb
Let me know if you run into any issues.

**Comment by TheoWolf** [comment]
Stalled ticket!
