### ISSUE TITLE
Issues loading .wmv viles

### ISSUE THREAD

**Issue by istallworthy** [databrary/datavyu#325]
**Describe the bug**
Hi there, 
I am having difficulties using .wmv files with Datavyu and I'm wondering if you have a particular plugin suggestion or other suggestion? Basically the file loads but then will not play/start/stop smoothly and seems to freeze a lot. 

**Expected behavior**
I would love to be able to successfully code .wmv files!

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  OSX (but we've found this to also occur on Windows)
 - Datavyu version 1.3.7]

**Additional context**

**Comment by TheoWolf** [comment]
@istallworthy We developed a new plugin called FFmpeg that will be able to read wmv format. You can find in the latest development version 1.5.1 [here](http://datavyu.org/download.html). Please let me know if your issue is fixed.

**Comment by TheoWolf** [comment]
Will close this ticker, feel free to re-open it if you still have the same issue
