### ISSUE TITLE
Download link to DataVyu broken

### ISSUE THREAD

**Issue by adimercu** [databrary/datavyu#336]
The link to install any version of DataVyu is broken. When can we expect the file to be back up? 
<img width="1429" alt="Screen Shot 2020-03-24 at 3 52 54 PM" src="https://user-images.githubusercontent.com/61473662/77470755-91403a80-6de7-11ea-92a7-eb55ccfac91b.png">

**Comment by Amiyaz** [comment]
Yes I am having the same issue when I try to download and the same error message appears. 
<img width="435" alt="Error Message" src="https://user-images.githubusercontent.com/62621183/77471453-4ff85c80-6de0-11ea-8b0a-f328213b5e74.PNG">

**Comment by adimercu** [comment]
Good to know it is not just me.

**Comment by TheoWolf** [comment]
@adimercu @Amiyaz Sorry for the inconvenience we were working on the server,  the download should work now.
