### ISSUE TITLE
Datavyu does not open on Windows 10

### ISSUE THREAD

**Issue by ashleychuikay** [databrary/datavyu#337]
I have the development release of Datavyu on my Windows 10 laptop, and have been able to run the program successfully up until this week. I have tried to restart my computer, re-install Datavyu, install older releases of Datavyu, etc. 

I was able to open the program twice using "Run as Administrator", but that also inexplicably stopped working. Datavyu shows up in my "task manager" briefly when I try to run it, but disappears after (and no window ever pops up). I've also tried to install Datavyu on another Windows machine, and that didn't work either.

Please let me know if I can provide any other information! Thank you!

**Comment by adimercu** [comment]
This also just happened to me using a Macbook Pro. I was coding before lunch, took a break, closed the program. When I tried to get back to it this afternoon, it acted the exact same way you described. It would open for a second and then quit. Nothing on my computer changed within those few hours.

**Comment by johnerichards** [comment]
Me too. I tried 1.5.1_RC1 and 1.5.0 and same thing.  Multiple computers.

**Comment by johnerichards** [comment]
it was java, probably some download.  i did:
Searchbar / configure java / update / updatenow
and it works.  I am using 1.5.1-RC1-Windows

**Comment by ashleychuikay** [comment]
That was it - I wonder if Java was removed/changed during a recent Windows update. Thanks!

**Comment by TheoWolf** [comment]
@ashleychuikay @johnerichards we were updating our datavyu server. all versions should be working now
