### ISSUE TITLE
Datavyu will not open on my Windows computer

### ISSUE THREAD

**Issue by acaniglia** [databrary/datavyu#338]
**Describe the bug**

I have been unable to use Datavyu with remote video files because of playback issues. I would be able to play the video with audio for about a second before the audio would cut out and the picture would freeze, yet the time code would keep running. 
I tried to fix this by first uninstalling datavyu. Next, I deleted every file with "datavyu" in it from my hard drive. I then reinstalled the latest version of the program. However, the application would not open after I supposedly installed it. I tried the developmental release, but after installing it and trying to open it I got these two messages: "failed to locate JNI_CreateJavaVM" and "failed to launch JVM".
What seems to be the matter?

**Comment by TheoWolf** [comment]
@acaniglia We don't recommend streaming videos for a server/remotely with Datavyu, because it was not designed for that usage. A good practice is to always have your file in your local storage.
I would suggest having a fresh installation by:
* First deleting datavyu using this tool https://freemacsoft.net/appcleaner/
* Install Datavyu stable version (link http://datavyu.org/download.html ) 

Let me know if this works

**Comment by acaniglia** [comment]
>     * First deleting datavyu using this tool https://freemacsoft.net/appcleaner/
I am using a windows computer, is there a windows equivalent I should use?

**Comment by acaniglia** [comment]
How is this closed? You didn't even answer my last question about a Windows equivalent to the mac software you suggested.

**Comment by TheoWolf** [comment]
@acaniglia Sorry for that, it was an error, I closed the wrong issue.
There is no equivalent for Windows, you will have to delete the folders listed above to fully uninstall Datavyu.
```
%APPDATA%/Roaming/Databrary/
%APPDATA%/Local/datavyu
```
Steps:
* Open File Explorer/Windows Explorer
* Type %AppData% into the address bar and hit enter
* Navigate to the folder Roaming/Databrary/
* Delete all files
* Repeat same steps with Local/datavyu folder

Let me know if this fixed your issue

**Comment by acaniglia** [comment]
When I look for the datavyu folder in %AppData%/Local/Datavyu, I can't find it. Also I still cannot download the stable version from the datavyu website.

**Comment by acaniglia** [comment]
I just found an old version of the exe in my recycling bin. Reinstalled datavyu and it works. Thanks for your help.

**Comment by TheoWolf** [comment]
Please find Datavyu Stable here https://github.com/databrary/datavyu/releases/download/1.3.7/Datavyu-1.3.7-Windows.exe
We updated our website and your browser is probably using a cashed version.
