### ISSUE TITLE
Issue:Slowing Down Video without completely degrading audio

### ISSUE THREAD

**Issue by Edayle** [databrary/datavyu#350]
Hi Datavyu Users, 

I'm new to Datavyu and very interested in using this to transcribe parent-child interactions and code parent behaviors like responsiveness and their use of language support strategies. I'm having difficulty using Datavyu due to the fact that I can't use the shuttle tool, but that tends to make the video a little bit too slow for my needs, because it slows down the audio of the video too much. I reviewed the manual, and played around myself but I haven't been able to find a workaround! 
Thank you so much for your time and efforts in advance!

**Comment by tiger980303** [comment]
Hello,

I can help you with your question. Can you please tell me your full name, the name of your PI (or if you are the PI in your lab), and your institution? We’re keeping track of the kinds of questions people have and a list of the people who request Datavyu tech support. 

Thanks,
Tiger

**Comment by Edayle** [comment]
Hi Tiger!
Sure! My name  is Emily Quinn.
I’m the PI of my Lab and I’m at Oregon Health and Science University!
Warm regards,
EDQ

Emily Quinn Ph.D., CCC-SLP
Assistant Professor
Institute on Development and Disability
Department of Pediatrics
Oregon Health and Science University
quinnem@ohsu.edu<mailto:quinnem@ohsu.edu>
503-494-2263

**Comment by Edayle** [comment]
Hi Tiger,

I hope that this finds you well.
I can’t access the google link you sent me via GITHUB/ GOOGLE drive, when I follow the link it says that I don’t have permission.
Can you send directly to my OHSU email?

Thank you so much for your time and efforts in advance.
Sincerely,
EDQ

Emily Quinn Ph.D., CCC-SLP
Assistant Professor
Institute on Development and Disability
Department of Pediatrics
Oregon Health and Science University
quinnem@ohsu.edu<mailto:quinnem@ohsu.edu>
503-494-2263
