### ISSUE TITLE
VLC videos won't open in existing datavyu sheets, and I am unable to add videos.

### ISSUE THREAD

**Issue by jordanlharris93** [databrary/datavyu#354]
**Describe the bug**
Datavyu files open, but attached videos data are not opening with them. When I go to attach the data, an error message shows. I am using VLC.

**Expected behavior**
I am expecting to open a datavyu file and the video opens with it. I am also expecting to be able to add videos to datavyu files successfully.

**Screenshots**
![Screen Shot 2020-06-04 at 8 02 44 AM](https://user-images.githubusercontent.com/49735098/83783316-b954e100-a655-11ea-8a7a-ea470b27ff23.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Datavyu version 1.3.7

**Additional context**
This is in a lab computer on a University Server. A different computer in the lab has been able to open video files with no problem, attempting to do the same with 2 new computers are where there are issues

**Comment by tiger980303** [comment]
Dear Jordan,
I can help you with your question. Can you please tell me your full name, the name of your PI (or if you are the PI in your lab), and your institution? We’re keeping track of the kinds of questions people have and a list of the people who request Datavyu tech support.
Many thanks,
Tiger

**Comment by jordanlharris93** [comment]
Hello,

I was able to play around and solved the issue. I needed to install it in
the individual users folder and not on the PC itself which had admin
permissions issues.

Thanks,
Jordan
