### ISSUE TITLE
Crashing, etc. with Mac OS Catalina v10.15.5

### ISSUE THREAD

**Issue by ahreese** [databrary/datavyu#370]
I have version 1.5.1 of datavyu installed on my 2019 MacBook Air, and a couple issues have arisen as I've been creating a spreadsheet for the research I am doing. 

First, the app frequently crashes and a popup will appear on my screen asking if I'd like to reopen datavyu. Sometimes it goes back to what I had been working on, but once or twice it has deleted all of my progress pre-save. 

Second, when I click to add a new cell, it often creates a new cell in the middle of the dataset. For example, I'll wish to create a new cell on row 16 but it will prompt me to code into a new cell in row 3, setting all of my previous work off by one row.

**Comment by tiger980303** [comment]
Dear ahreese,
Thank you for contacting Datavyu Support. Can you please tell me your full name, the name of your PI (or if you are the PI in your lab), and your institution? We’re keeping track of the kinds of questions people have and a list of the people who request Datavyu tech support.

My apologies if you have recently contacted us. Please reply with your full name and if this is related to your last question and we will address your new Datavyu question.

Many thanks,
Tiger  
Datavyu Support Team

**Comment by ahreese** [comment]
My name is Annabelle Reese and my PI is Blair Youmans in Dr. Jeff Lockman’s lab at Tulane University. After installing the stable release of datavyu, I haven’t had the same issue I was having, but thank you for following up.

Best,
Annabelle

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
