### ISSUE TITLE
Datavyu not opening on Mac

### ISSUE THREAD

**Issue by lgreen38** [databrary/datavyu#373]
Datavyu will not run on my device. I am using MacOS Catalina. Early in the day, I was able to run Datavyu. However, when I went to open it later, it would try to open, but was never successful. I have uninstalled and reinstalled the latest stable version of Datavyu and am still experiencing this problem. Please let me know what I should try next. Thank you!

**Comment by TheoWolf** [comment]
@lgreen38 The issue is fixed, please try datavyu and let us know if it is working for you. Sorry for the inconvenience.

**Comment by lgreen38** [comment]
Working now. Thanks.
