### ISSUE TITLE
Datavyu quits immediately after opening (several computers)

### ISSUE THREAD

**Issue by mtrizzo** [databrary/datavyu#374]
**Describe the bug**
Datavyu will open and then immediately quit upon opening. This is happening across 4 computers (all Macs) and just started happening today. The issue occurs when opening old and new files.

Thank you for your time,
Michael Rizzo (CDSC Lab, NYU)
mtrizzo@nyu.edu

**Comment by mtrizzo** [comment]
All computers are using stable release 1.3.7. and had been using datavyu successfully for several months. We uninstalled and reinstalled on one of the computers, but it did not resolve the issue.

**Comment by TheoWolf** [comment]
@mtrizzo The issue is fixed, please try datavyu and let us know if it is working for you. Sorry for the inconvenience.

**Comment by mtrizzo** [comment]
Thank you!
