### ISSUE TITLE
Hitting Pause Button Skips Frames

### ISSUE THREAD

**Issue by eks48pitt** [databrary/datavyu#377]
We are working on transcribing videos from recorded Zoom meetings. When I hit the pause button, the video skips ahead a few frames so it makes it quite challenging to get accurate onset times because even if you rewind, it still skips frames when you hit pause again.

**Comment by tiger980303** [comment]
Dear eks48pitt,
Thank you for contacting Datavyu Support. Can you please tell me your full name, the name of your PI (or if you are the PI in your lab), and your institution? We’re keeping track of the kinds of questions people have and a list of the people who request Datavyu tech support.

My apologies if you have recently contacted us. Please reply with your full name and if this is related to your last question and we will address your new Datavyu question.

Many thanks,

Tiger  
Datavyu Support Team

**Comment by eks48pitt** [comment]
Hello,

My name is Erica Schweitzer and my PI is Melissa Libertus, we work for the University of Pittsburgh. This is the second time I've submitted a question and this one does not have anything to do with the first.

Best,

Erica


Erica Schweitzer

Research Assistant

Parents Promoting Early Learning

Learning, Research & Development Center

University of Pittsburgh

3939 O'Hara St.

Pittsburgh, PA 15260

(412) 624-7058


University of Pittsburgh

Class of 2019

Psychology


________________________________

**Comment by tiger980303** [comment]
Hi Erica,

What version of Datavyu are you using? And what OS (Windows or Mac) are you using?

Thanks,
Tiger

**Comment by eks48pitt** [comment]
Hello,

I'm using 1.5.1 on Windows.

Best,

Erica


Erica Schweitzer

Research Assistant

Parents Promoting Early Learning

Learning, Research & Development Center

University of Pittsburgh

3939 O'Hara St.

Pittsburgh, PA 15260

(412) 624-7058


University of Pittsburgh

Class of 2019

Psychology


________________________________

**Comment by tiger980303** [comment]
Hi Erica,

It is a known issue in 1.5.1 for Windows OS for the simple reason that the FFmpeg plugin will force the video to seek to the controller timestamp to make sure that the time on the video, datavyu video controller and the cell are synced, we are working optimizing the FFmpeg plugin for different types of hardware but should be improved in future versions.

I would recommend using Datavyu 1.3.7 for your case, try to have your videos in mp4 format and use the JavaFX plugin when you select your video. We deprecated VLC and Quicktime plugins and we strongly recommend using JavaFX on Datavyu 1.3.7.

Let me know if this help solve your issue!

Thanks,
Tiger

**Comment by eks48pitt** [comment]
Thanks I will give it a try.

Erica


Erica Schweitzer

Research Assistant

Parents Promoting Early Learning

Learning, Research & Development Center

University of Pittsburgh

3939 O'Hara St.

Pittsburgh, PA 15260

(412) 624-7058


University of Pittsburgh

Class of 2019

Psychology


________________________________

**Comment by eks48pitt** [comment]
Hello,

The video is already in the mp4 format. The frame rate is 25.00 frames/second and I can't find the resolution.

Erica


Erica Schweitzer

Research Assistant

Parents Promoting Early Learning

Learning, Research & Development Center

University of Pittsburgh

3939 O'Hara St.

Pittsburgh, PA 15260

(412) 624-7058


University of Pittsburgh

Class of 2019

Psychology


________________________________

**Comment by tiger980303** [comment]
Hi Erica,

It's possible that the recording is corrupted or something is not working properly between Datavyu and your machine. If it's possible, could you try to use a different machine and see if it works on Datavyu 1.3.7 (JavaFX) or Datavyu 1.5.1 (FFmpeg). If it's not possible, can you try using a different [video ](https://datavyu.org/user-guide/downloads/DatavyuSample.zip)to see if the same issue persists? These are not solutions to fix your issue, but it will let us know whether there is an issue with your video, your machine, or Datavyu.

Finally, what program did you use to convert your video or was it originally in an .mp4 format? If it was originally in .mp4 format or you didn't use Handbrake to convert the video, then can you use [Handbrake ](https://handbrake.fr/)to convert your video to .mp4? Even if your video is already in the .mp4 format, use the Handbrake program to convert to .mp4. 

Thanks,
Tiger

**Comment by eks48pitt** [comment]
Hi,

None of these suggestions helped, I cannot get a video to attach to a file at all.

Erica


Erica Schweitzer

Research Assistant

Parents Promoting Early Learning

Learning, Research & Development Center

University of Pittsburgh

3939 O'Hara St.

Pittsburgh, PA 15260

(412) 624-7058


University of Pittsburgh

Class of 2019

Psychology


________________________________

**Comment by tiger980303** [comment]
Hi Erica,

If it's possible, could you send me the file(s) or a link to the file(s) that is causing the issue so that we can test it on our end? If this is not possible, we can schedule a zoom call and see if I can help you then. 

Thanks,
Tiger

**Comment by eks48pitt** [comment]
Hi,

Unfortunately due to confidentiality reasons, neither of those suggestions is something we can do. Is there anything else you can think of?

Erica


Erica Schweitzer

Research Assistant

Parents Promoting Early Learning

Learning, Research & Development Center

University of Pittsburgh

3939 O'Hara St.

Pittsburgh, PA 15260

(412) 624-7058


University of Pittsburgh

Class of 2019

Psychology


________________________________

**Comment by tiger980303** [comment]
Hi Erica,

Did you try using the sample video we sent last time and did it produce the same error?

Also, can you send me the following for your computer? This issue may be related to your machine rather than the video.
(The following can be found under right-clicking "This PC", select "Properties", click on "Device Manager" on the left)
-Graphic Card (can be found under Device Manager -> Display Adapters): 
-RAM (can be found under Properties): 
-Processor (can be found under Properties):
-# of Cores (can be found under Device Manager -> Processors, divide the numbers by 2):

Thanks,
Tiger

**Comment by eks48pitt** [comment]
Hi,

Yes I used the sample video and it produced the same issues.
Here are the specs you asked for:
Graphics 630
RAM:16.0GB
Processor: Intel (R) Core(TM) i7-9850H CPU @ 2.60 GHz 2.59 GHz
Core: 6 I think


Erica


Erica Schweitzer

Research Assistant

Parents Promoting Early Learning

Learning, Research & Development Center

University of Pittsburgh

3939 O'Hara St.

Pittsburgh, PA 15260

(412) 624-7058


University of Pittsburgh

Class of 2019

Psychology


________________________________

**Comment by tiger980303** [comment]
Hi Erica,

Can you use Handbrake https://handbrake.fr/ to convert your videos into .mp4 (even if it's already in .mp4)? You would just insert the video into the program and hit run on the bottom. Once it's converted, test it out and see if it's still producing the same issue.

Thanks,
Tiger

**Comment by eks48pitt** [comment]
Hello,

I've tried that now yesterday and today both times with the sample video and it did not change anything. I just hit the encode button in Handbrake because I saw no run button. Then once the program said it was done, I closed the program. I don't know if I did something incorrect but one of my coworkers and I both can't think of what else to do in that program.

Erica


Erica Schweitzer

Research Assistant

Parents Promoting Early Learning

Learning, Research & Development Center

University of Pittsburgh

3939 O'Hara St.

Pittsburgh, PA 15260

(412) 624-7058


University of Pittsburgh

Class of 2019

Psychology


________________________________

**Comment by tiger980303** [comment]
Hi Erica,

Can you try to do a clean re-install of Datavyu by uninstalling Datavyu via C:\Users\NAME\AppData\Local\Datavyu. There should be an application called "uninst000". Once it's uninstalled, go to Datavyu.org and re-install Datavyu 1.5.1 and see if it works. If it doesn't, do the uninstallation again and try it with 1.3.7.

Thanks,
Tiger

**Comment by eks48pitt** [comment]
Hi,

This might have worked. I am going to try to use the program, I will let you know if something else comes up. Thank you!

Erica


Erica Schweitzer

Research Assistant

Parents Promoting Early Learning

Learning, Research & Development Center

University of Pittsburgh

3939 O'Hara St.

Pittsburgh, PA 15260

(412) 624-7058


University of Pittsburgh

Class of 2019

Psychology


________________________________
