### ISSUE TITLE
Ffmpeg plugin cannot load file

### ISSUE THREAD

**Issue by ebdun** [databrary/datavyu#378]
When adding data in Datavyu, the selected video produces an error that says "This plugin cannot load this file"
**To Reproduce**
1. Go to 'add data' in the controller
2. Click on any video
3. See error

**Expected behavior**
The video opens in the controller. 

**Screenshots**
<img width="962" alt="error message" src="https://user-images.githubusercontent.com/69917852/90669489-bfec0100-e21f-11ea-847c-25b5a73aa26f.png">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Datavyu version 1.5.1

**Additional context**
Using VLC for videos.

**Comment by tiger980303** [comment]
Dear ebdun,

Thank you for contacting Datavyu Support. Can you please tell me your full name, the name of your PI (or if you are the PI in your lab), and your institution? We’re keeping track of the kinds of questions people have and a list of the people who request Datavyu tech support.

My apologies if you have recently contacted us. Please reply with your full name and if this is related to your last question and we will address your new Datavyu question.

Many thanks,
Tiger  
Datavyu Support Team

**Comment by ebdun** [comment]
Hello,
My name is Eden Dunford. I am at the Duke Center for Autism and Brain Development and my PI is Dr. Geraldine Dawson.

Thank you.

**Comment by tiger980303** [comment]
Hi Eden,

What file type are you adding into Datavyu (.mov, .mp4, .mpg)? If you are using .mov files, we recommend that you convert your files to .mp4 and see if this solves the issue.

Let me know if this helps!

Thanks,
Tiger

**Comment by ebdun** [comment]
I am using .mov files but converting to .mp4 has not solved the issue.

**Comment by tiger980303** [comment]
Hi Eden,

Does your machine have Java installed? Datavyu requires Java 1.6 or higher. Many operating systems include Java by default, but if you are unsure whether or not your computer has Java installed already, go ahead and click the link to install as the installation will override older versions of Java or simply install Java if you did not have it.
https://www.java.com/en/download/manual.jsp 

After installing Java, restart your computer and reload Datavyu. Add in your data and see if the same error occurs.

Let me know if this solves your issue!

Thanks,
Tiger

**Comment by ebdun** [comment]
Updating Java was the solution. Wonderful, thank you!
